- class/core/wc4bp-component.php
- class/core/wc4bp-redirect.php
- class/core/wc4bp-screen.php
- class/wc4bp-manage-admin.php
- class/wc4bp-manager.php
https://github.com/Themekraft/wc4bp/issues/15
> Fixing the duplicate cart and duplicate default page content

- class/class-tgm-plugin-activation.php
- class/wc4bp-manager.php
- class/wc4bp-required.php
- wc4bp-basic-integration.php
https://github.com/Themekraft/wc4bp/issues/6
> Adding the tgm requirement plugin.

- class/wc4bp-manage-admin.php
- class/wc4bp-manager.php
- class/wc4bp-required.php
- wc4bp-basic-integration.php
https://github.com/Themekraft/wc4bp/issues/19
> Adding more validation for requirements.

- class/wc4bp-required.php
https://github.com/Themekraft/wc4bp/issues/19
> Fixing the bulk activation

- class/core/wc4bp-component.php
- class/wc4bp-myaccount.php
- templates/shop/member/plugin.php
Fixing the redirect problem
https://github.com/Themekraft/wc4bp/issues/7
Fixing the checkout page not found
https://github.com/Themekraft/wc4bp/issues/22
> Multiples fixes

- .travis.yml
- class/core/wc4bp-component.php
- class/wc4bp-myaccount-content.php
- class/wc4bp-myaccount.php
- composer.json
- phpcs.ruleset.xml
- phpunit.xml.dist
- readme.md
- readme.txt
- templates/shop/member/plugin.php
- tests/WC4BP_LoaderTest.php
- tests/bootstrap.php
- tests/test-sample.php
Adding the order view details and the download content.
> Multiple Fixxing

- admin/admin-ajax.php
- admin/admin.php
- class/core/wc4bp-component.php
- class/wc4bp-myaccount-content.php
- class/wc4bp-myaccount.php
- templates/shop/member/plugin.php
- wc4bp-basic-integration.php
https://github.com/Themekraft/wc4bp/issues/31
https://github.com/Themekraft/wc4bp/issues/28
https://github.com/Themekraft/wc4bp/issues/26
https://github.com/Themekraft/wc4bp/issues/29
> Multiples fixing

- admin/admin-delete.php
- admin/admin-pages.php
- admin/admin-sync.php
- admin/admin.php
- admin/css/admin.css
- admin/views/html_admin_delete_all_settings.php
- admin/views/html_admin_header.php
- class/core/wc4bp-component.php
- class/core/wc4bp-redirect.php
- class/wc4bp-manager.php
- class/wc4bp-myaccount.php
- templates/shop/member/plugin.php
- wc4bp-basic-integration.php
https://github.com/Themekraft/wc4bp/issues/41
https://github.com/Themekraft/wc4bp/issues/39
https://github.com/Themekraft/wc4bp/issues/30
https://github.com/Themekraft/wc4bp/issues/9
https://github.com/Themekraft/wc4bp/issues/7
> Multi Fixing

- class/core/wc4bp-component.php
- class/core/wc4bp-redirect.php
- class/core/wc4bp-sync.php
- class/wc4bp-myaccount.php
https://github.com/Themekraft/wc4bp/issues/43
> Fixing the redirection problem to return to the shop.

- class/core/wc4bp-component.php
- class/core/wc4bp-redirect.php
Fixing the redirect problem when history are disabled. Fixing the redirect default when the cart tabs are disabled
https://github.com/Themekraft/wc4bp/issues/47
https://github.com/Themekraft/wc4bp/issues/7
> More Fixing

- admin/admin-pages.php
- admin/admin.php
- admin/css/admin.css
- admin/views/html_admin_header.php
- admin/views/html_admin_my_account_tabs.php
- admin/views/html_admin_pages_forms_table.php
- admin/views/html_admin_pages_thickbox.php
- admin/views/html_admin_profile_sync.php
- admin/views/html_admin_shop_disable.php
- admin/views/html_admin_shop_tabs.php
- class/wc4bp-base.php
- class/wc4bp-manager.php
https://github.com/Themekraft/wc4bp/issues/9
> Integrating the visual part of the freemius.

- admin/admin-sync.php
- admin/admin.php
- class/core/wc4bp-component.php
- class/core/wc4bp-redirect.php
- class/wc4bp-manager.php
- class/wc4bp-myaccount.php
- class/wc4bp-woocommerce.php
https://github.com/Themekraft/wc4bp/issues/54
https://github.com/Themekraft/wc4bp/issues/50
https://github.com/Themekraft/wc4bp/issues/53
> Multiples fixings

- class/core/wc4bp-redirect.php
- class/wc4bp-base.php
https://github.com/Themekraft/wc4bp/issues/57
> Múltiple fixing

- admin/views/main/html_admin_my_account_tabs.php
- class/core/wc4bp-component.php
- class/wc4bp-manager.php
- class/wc4bp-myaccount.php
- templates/shop/member/plugin.php
Fixing the disable my account tabs in the free version. 
Now the my account tabs is showing to starter plan, and only is possible to disabled it in professional
https://github.com/Themekraft/wc4bp/issues/59
> Disable my account tabs in the free version

- class/includes/wc4bp_requirements.php
- class/wc4bp-required-php.php
- wc4bp-basic-integration.php
Fixing incompatibility for the requirement library.
> Fixing incompatibility for the requirement library.

- admin/admin-ajax.php
- admin/admin-sync.php
- class/wc4bp-myaccount.php
https://github.com/Themekraft/wc4bp/issues/69
> Fix SYNC BUDDY PRESS FIELDS

- class/includes/class-tgm-plugin-activation.php
- class/wc4bp-required.php
- wc4bp-basic-integration.php
* Changing the requirement library to use a custom internal id.
* Changing the dependency order.
> * Adding custom message to check dependency.

- class/wc4bp-activity-stream.php
> Revert "Feature/settings activity stream"

- class/core/wc4bp-component.php
> Revert "Fix:Las paginas creadas no están saliendo en el orden que se les asig…"

- class/core/wc4bp-redirect.php
- class/wc4bp-redefine-functions.php
- class/wc4bp-woocommerce.php
fixes #253
fixes #252
fixes #250
> Fix the url redirection

- admin/admin-ajax.php
The field was no being updated on the process of Sync Woo & BP fields.
> Fix issue related with First Name on Billing Address (Xprofile).
